TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += SMRTMON.db
DB += channels.db
DATA += SMRTMON.proto

#=======================================
include $(TOP)/configure/RULES
